khanelimac_khaneliman_ssh_key: ENC[AES256_GCM,data:WUSNCrc1JpRxHimyCtL2mLi9Kd1jZR62Wh9IP+WHszP2s77RvzeSjwrHi4hOy2ZZYZ2rvzhg+PbruOqF6NoUnNtHqdvwH8vvmls7eldbWm93J5wHZ+weZde6iPonhG5jxEPKeKUZ8rcY8Xq8Ef7Wx2jBwpWusbQy8JSg4kXyNZqNymQqKqb2Cph8SLakwoMkcUGi7PEUX4c6EBevKhgC1h0c8uNdN6FGeaVDuIsbVLwHg+AXjUd7ZudUwjtBexU6Hqo13Knt/tplaMddQcV9lrixhQGCdQEKP9D3d1P3BCkT9WP6/la0TiBOnphp0BfrV7mxGm/o31LB2mP6Rzm7QEfNs/UWS3iJjaM448MF5cylRcQkwCQtHk5CgxgEucefT4wkGaRklD/aMHG8Cq5wObE3m69VlnJhvCfJ2d2rqC3HxPPDam94LGw1pp8QMOyefi1i4HWLcEgNYYIr8Ap5N1helhGDPkUl1Kp1YeT3B12+qbT0H8ojgWoaqD5kH69xeuFsht4btZg0jPl6qnkxJj+l17WH+rbnWueHAJgMN/Za/+o=,iv:8Af58OxQ3Gl5yHANjjFoY4yPO393vrfGDpshYzuPNwM=,tag:UTNAj0oPitPp52i/Tuy2FA==,type:str]
khanelimac_ssh_key: ENC[AES256_GCM,data:AfbSBDn67iMNcc3saakiC1AdfvEXR3HO9GuOTbyX7mw5VNCePs9aRt8gHeFq1kYk+GC15PsFLW4FwITND9tqIjlgj7VFhcyFsKQPTaXrFxTHQ15PjDfqqV6KYiDEOnb9qoZNCZ4s3ZQhiB/m6twSKfthqC0yGzc+46JUZGfU+/QQSyHu1N5lLJ42CyjWKJPtifggoB0z9kjxzNsKV9mgc3Q/rI4lyHbLJ8OvIPWlFs58Un3OywPr3AK7MWvzPmoy2nbLj+xIn1TQ0xZudsXO8qao5R/ZqluX5vMxDqucU2aPjI9//QoCNqIIiNzqDD9DV9IWgKqQRV5uHHtyeUcWfLjrNTMUoREG0RJZedwY788vWxn/8u0Mvf922Ga/Uig1youOIZqN/QRXGEQL4HqYzvRoaYSEw5OQhQg8XPoq4JkVgyJt+bTj1ayjwZSZ+tsuCwKEASeJPknFEfP7L/OkHzKPEbB1g+AdquuoSblEpQNPgLoGnpLsP+f9KHdoYQSXZ8pb,iv:f/Wz5C69TivEIHJ1D3i83ClimldgvCKg8XHq+YH44BY=,tag:ntg8cKcn7QTCXoOP/LmqYQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1547vqtqhgtxu54eewxwttjsfd85w0lm4f46fyxxhnx2ydxt7kyxs36ts2d
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTT1JYKzNMcDZCMFM1dW9J
        WWZoT0c3SXdCZGZKSlo3d29mSVNOdDRPZERzCnVFUnV1MytwRnU3KzF4cFE4N1Jx
        bmJmVm9PSTRERncxOEtLUndiZVluZWsKLS0tIDdYVGt2eWttMmRnY0hZVXAyblht
        VHNubExHMUZySmJZR3hoOU1mS2s5RVkKhiaz/vYy/r5+qnIawH361fc6ON+HrMgt
        yaFg09UiWuNGOlbbzDOHdzm47F5mrP4XlBkZo/SAs9IBuo8w3+Z7qg==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1q2qaahrx4chvsa5g7xqwrwk28mld6kn4md8crcrqg046m8yt2efsugl8vr
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjMTRoSUVMVnR3VEtaai9p
        MnRDZHNyM24vUVdjSUp3dnFHamt2a0hZaFdRCkVLVGJwVy9rWmkxR0RSbHNPVXpL
        MlIyQS9mUFYwbjhnMkM1YzZiNkxFTE0KLS0tIDRDT3B3dk81RVBQMkdibU5sYzVF
        SDdMbFpjeHg4WWhUUWZ3YXAzTDBZYUEKCp8LAYoakc/73tVuYnIH7RKGmrut9IM8
        zPC5geXsnU4W6PYGC1da6Pk94lqqKJOz7vLJBLgg/VHfwvXSnI4CCg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-01-04T18:47:39Z"
  mac: ENC[AES256_GCM,data:GS7Q7/BqHExdySh7IWuB2kwq74csfrAQBQ+DRBxDZGhD1yACaZ0kwXq+a2Q74fqyV79QYWvtRMN9czAqXy6jw8VfYPtiSHPwRj3N+LqU4eqbaCkxn//HRQ3jfyp7KODcLhOlzJiEFJN+M6LQQvMLHBAAzYhYOiFFVqMQVJqgITM=,iv:0i7SbPczKkzi27TbE0a1nKKBw7xgEd5pw69T+4XhJBU=,tag:7eu0+dyFQDAspKmpbCXidg==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.9.2
