name: Check
on: [push, pull_request, workflow_dispatch]
jobs:
  checks:
    name: Check expressions on ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        arch: [aarch64-darwin]
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - name: Check Nix flake inputs
        uses: DeterminateSystems/flake-checker-action@v12
    # - uses: cachix/install-nix-action@v31
    #   with:
    #     install_url: https://nixos.org/nix/install
    #     extra_nix_config: |
    #       auto-optimise-store = true
    #       access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
    #       experimental-features = nix-command flakes
    #       system = ${{ matrix.arch }}
    # - uses: cachix/cachix-action@v12
    #   with:
    #     name: andrea11
    #     authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    # - name: clear hostedtoolcache
    #   run: rm -rf /opt/hostedtoolcache
    # - name: run flake check
    #   run: nix flake check --system ${{ matrix.arch }}
