name: Formatting Check
on: [push, pull_request, workflow_dispatch]
jobs:
  checks:
    name: Check expressions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
        with:
          install_url: https://nixos.org/nix/install
      - run: nix fmt .
